name: backend-ci

on:
  push:
    branches: [main]
    paths: ["**/*.go", "Dockerfile", ".github/workflows/backend-ci.yml"]
  pull_request:
    paths: ["**/*.go", "Dockerfile"]

permissions:
  contents: read
  packages: write

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Tidy & Test
        run: |
          go mod tidy
          go test ./... -v

      - name: Set image tag (by commit SHA)
        run: echo "IMAGE=ghcr.io/${{ github.repository }}:sha-${{ github.sha }}" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image (linux/amd64)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE }}

      - name: Notify infra-live (repository_dispatch)
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INFRA_REPO_PAT }}
          repository: Vadim-12/infra-live
          event-type: backend-image-updated
          client-payload: |
            { "image": "${{ env.IMAGE }}", "env": "dev" }
